### ISSUE TITLE
Support HTTP Cache

### ISSUE THREAD

**Issue by fkorotkov** [uber/makisu#101]
It will be nice to support not only Redis but a simple PUT/GET HTTP Cache. Similar to what Buck, Bazel, Pants and other build system use.

**Comment by yiranwang52** [comment]
Just out of curiosity, what server are you running and how do you manage TTL?

**Comment by fkorotkov** [comment]
@yiranwang52 it's a proxy to Google Cloud Storage with buckets for each repository with different object lifecycle. Also PRs only have read access from the main storage and can write to a separate "namespace" to make sure it can't corrupt/poison production.

**Comment by yiranwang52** [comment]
So you want
```
GET /artifacts/key/[key]
PUT /artifacts/key
```
As described on https://buckbuild.com/concept/http_cache_api.html?

**Comment by fkorotkov** [comment]
In my case I used the cache with Gradle and Bazel and the cache exposes following API:

```
GET /[key]
PUT /[key]
```

Which is compatible both with Gradle and Bazel since `key` can contain `/`. My impression was that Buck is using the same API but now it looks like `PUT` is a bit different. Sorry about not clarifying it all in my initial comment. 😔

**Comment by yiranwang52** [comment]
I think we can make this interface more friendly to 3rd party plugins, and implement the easiest one...

**Comment by fkorotkov** [comment]
As far as I know simple GET/PUT is sophisticated enough for Gradle, Bazel and Pants build systems. 

**Full disclaimer:** I'm biased towards GET/PUT API since a CI I'm working on [support this API out of the box](https://cirrus-ci.org/guide/writing-tasks/#http-cache) specifically to speed up builds for systems that support remote caching. I would love also make building Docker containers much faster on Cirrus CI by switching from _kaniko_ to _makisu_ in that case.

**Comment by fkorotkov** [comment]
Also I don't think there is something simpler then just GET/PUT. Vanilla Nginx and most proxies can do this out of the box.

**Comment by fkorotkov** [comment]
Just looked up Artifactory API since A LOT of companies have Artifactory installations and they also support [PUT/GET API for uploading artifacts](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeployArtifact). They just require to pass an authorization token via a header. So maybe also add a way to pass specific headers for requests to http cache?

**Comment by apourchet** [comment]
OK, will start implementing this interface:
```
GET /[key]
PUT /[key] 
   <request body>
```
Pluggable headers through command arg flags is fairly common for those things so we'll add that too.
