### ISSUE TITLE
Redis client library is outdated, doesn't support cluster mode

### ISSUE THREAD

**Issue by hatemosphere** [uber/makisu#127]
Well, topic says it all - https://github.com/uber/makisu/blob/master/Gopkg.lock#L173-L182 the repo with client library is archived in favor of upstream https://github.com/gomodule/redigo. Apparently, upstream repo also does not support cluster mode, so it might be beneficial to migrate to well-maintained library like this one https://github.com/go-redis/redis, to kill two birds with one stone.

**Comment by hatemosphere** [comment]
In practice, this what happens when you try to run makisu against Redis cluster:
```json
{"level":"error","ts":1545209445.746716,"msg":"Failed to push cache: store tag mapping (65b6ee26,902f6a63afa7effffc16c0c14bb3dbf5bbe4926dd689c2aaddc8e792044fb5ab,5c20fb913c01b4f9b748d2fcfcb455f77a8a709ec86300a98b80280d730e7616): MOVED 15630 x.x.x.x:6379; store tag mapping (d0b17d2e,f7dae4047cccd0e0ce35a4e758f2b7b60707b9f54ba5cc52c53837a6acf31ca5,f9a83abf7e5603e1bd3d8242525dab840dba8b23921c0385460b074f06c8aa0a): MOVED 8778 x.x.x.x:6379"}
```

**Comment by yiranwang52** [comment]
Need a few more days to create a new release.
