### ISSUE TITLE
Kernel Panic in k8s when using stupidly large number

### ISSUE THREAD

**Issue by nnordrum** [uber/makisu#133]
https://github.com/uber/makisu/blob/master/lib/builder/step/fixtures.go#L32

```
sh-4.2$ makisu
panic: user: unknown userid 1016600000

goroutine 1 [running]:
github.com/uber/makisu/lib/builder/step.init.0()
        /root/go/src/github.com/uber/makisu/lib/builder/step/fixtures.go:34 +0x29d
sh-4.2$ id
uid=1016600000 gid=0(root) groups=0(root),1016600000
```

my local docker seems to be okay that that UID, so maybe it's the base container?

**Comment by yiranwang52** [comment]
I dont think this is a Makisu specific issue. The base container probably cannot handle it.

**Comment by nnordrum** [comment]
Agreed, BUT, Makisu could handle it a lot better when it happens... that’s where I was going with this...

**Comment by yiranwang52** [comment]
It's caused by:
```
	u, err := user.Current()
	if err != nil {
		panic(err)
	}
```
The panic was intentional.

The error message is:
```
panic: user: unknown userid 1016600000
```
Which I think is pretty reasonable.
