### ISSUE TITLE
master fails to build images with `failed to load manifest storage dir:....`

### ISSUE THREAD

**Issue by geekflyer** [uber/makisu#136]
Current master (https://github.com/uber/makisu/commit/e47f057f52ef6a9a4ce9ed0458344860477efb69)  of makisu fails to run `makisu build` with:
```sh
{"level":"fatal","ts":1545782991.790016,"msg":"Failed to load manifest storage dir /makisu-storage/manifest/cache: file does not exist"}
```

Probably #134 broke it.

Reproduction:
```sh
➜  makisu-use docker run -it --rm  \
        -v /var/run/docker.sock:/docker.sock \
        -v $HOME/.config/gcloud:/root/.config/gcloud -e DOCKER_HOST=unix:///docker.sock \
        -v $(pwd):/makisu-context \
        -v /tmp/makisu-storage:/makisu-storage \
        makisu-gcr:latest build --modifyfs=true --load --registry-config=/makisu-context/registry.yaml --redis-cache-addr=10.0.0.11:6379 -t=gcr.io/my-project/makisu -f /makisu-context/test.Dockerfile ./
{"level":"info","ts":1545782991.7671587,"msg":"Starting Makisu build (version=v0.1.6-11-ge47f057)"}
{"level":"fatal","ts":1545782991.790016,"msg":"Failed to load manifest storage dir /makisu-storage/manifest/cache: file does not exist"}
```

**Comment by evelynl94** [comment]
do you mind show us the file tree under `/tmp/makisu-storage/manifest/cache`?

**Comment by geekflyer** [comment]
here's the contents of my manifest cache:
```sh
➜  dev ls -la /tmp/makisu-storage/manifest/cache
total 0
drwxr-xr-x  8 christian  wheel  256 Dec 20 14:37 .
drwxr-xr-x  4 christian  wheel  128 Dec 26 03:50 ..
drwxr-xr-x  2 christian  wheel   64 Dec 23 02:47 Y2hyaXN0aWFuLXBsYXlncm91bmQvbWFraXN1L2xhdGVzdA==
drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 bGlicmFyeS9hbHBpbmUvbGF0ZXN0
drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 bGlicmFyeS9ub2RlLzg=
drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 c29sdnZ5LWRldi9jaHJpc3RpYW4tcGxheWdyb3VuZC9tYWtpc3UtdGVzdDEvbGF0ZXN0
drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 c29sdnZ5LWRldi9jaHJpc3RpYW4tcGxheWdyb3VuZC9tYWtpc3UvbGF0ZXN0
drwxr-xr-x  2 christian  wheel   64 Dec 23 02:47 c29sdnZ5LWRldi9zb2x2dnktZGV2L2NocmlzdGlhbi1wbGF5Z3JvdW5kL21ha2lzdS9sYXRlc3Q=
```

**Comment by geekflyer** [comment]
fyi, after emptying the `/tmp/makisu-storage` directory I get a different, but still confusing error:

```sh
{"level":"info","ts":1545792916.383053,"msg":"* Step 2/2 (commit,modifyfs) : RUN echo foo  (4da340ed)"}
failed to execute build plan: execute stage: build stage 0: build node: do execute: execute step: cmd start: exec: "sh": executable file not found in $PATH
```

reproduction:

```dockerfile
FROM alpine

RUN echo foo
```

```sh
docker run -it --rm  \
        -v /var/run/docker.sock:/docker.sock \
        -v $HOME/.config/gcloud:/root/.config/gcloud -e DOCKER_HOST=unix:///docker.sock \
        -v $(pwd):/makisu-context \
        -v /tmp/makisu-storage:/makisu-storage \
        makisu-gcr:latest build --modifyfs=true --load --registry-config=/makisu-context/registry.yaml -t=gcr.io/my-project/christian-playground/makisu -f /makisu-context/test.Dockerfile ./
```

**Comment by evelynl94** [comment]
> here's the contents of my manifest cache:
> 
> ```shell
> ➜  dev ls -la /tmp/makisu-storage/manifest/cache
> total 0
> drwxr-xr-x  8 christian  wheel  256 Dec 20 14:37 .
> drwxr-xr-x  4 christian  wheel  128 Dec 26 03:50 ..
> drwxr-xr-x  2 christian  wheel   64 Dec 23 02:47 Y2hyaXN0aWFuLXBsYXlncm91bmQvbWFraXN1L2xhdGVzdA==
> drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 bGlicmFyeS9hbHBpbmUvbGF0ZXN0
> drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 bGlicmFyeS9ub2RlLzg=
> drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 c29sdnZ5LWRldi9jaHJpc3RpYW4tcGxheWdyb3VuZC9tYWtpc3UtdGVzdDEvbGF0ZXN0
> drwxr-xr-x  2 christian  wheel   64 Dec 25 02:23 c29sdnZ5LWRldi9jaHJpc3RpYW4tcGxheWdyb3VuZC9tYWtpc3UvbGF0ZXN0
> drwxr-xr-x  2 christian  wheel   64 Dec 23 02:47 c29sdnZ5LWRldi9zb2x2dnktZGV2L2NocmlzdGlhbi1wbGF5Z3JvdW5kL21ha2lzdS9sYXRlc3Q=
> ```

My original guess was one of these sub directories missed a file call `data`, but this is the first time I saw this error...I think makisu should cleanup incomplete cache files when reload.

**Comment by yiranwang52** [comment]
Okay, about the second issue (sh not found), dockerhub experienced some connection problem for the past few hours, and seems it has recovered. Makisu might have swallows the connection issues.
About the original first issue, we need to add some cleanup if directory content is not as expected.
