### ISSUE TITLE
Problem with WORKDIR

### ISSUE THREAD

**Issue by nnordrum** [uber/makisu#143]
https://github.com/uber/makisu/blob/master/lib/builder/step/base_step.go#L96

It's related to that, but I can't for the life of me create a small example that fails... I'm just putting this here to have _something_ if somebody hits this again. (I'm still trying to create a small example that fails)

**Comment by nnordrum** [comment]
I know `WORKDIR` is supported, but in this weird case it fails, so I opened this issue. I don't expect a fix based on the lack of information provided.

**Comment by yiranwang52** [comment]
Did makisu crash? or the image it produced doesn't have WORKDIR set?
