### ISSUE TITLE
Pushing to Docker Hub with docker config creds

### ISSUE THREAD

**Issue by cdupuis** [uber/makisu#157]
I tried various combinations in the `--registry-config` to pass in creds for pushing to Docker hub without any success. All attempts failed. 

Could you provide instructions on how I could use Docker hub with makisu?

I'm sure this isn't really a bug but I wasn't able to join the Slack workspace linked from the README as it only allows users with uber.com emails.

**Comment by yiranwang52** [comment]
#158 will fix the slack link.

In the meantime, do you mind sharing the configs you have tried so we can repro?

**Comment by yiranwang52** [comment]
I think this issue should have been fixed by #178
