### ISSUE TITLE
Makisu deleted all my files! (in my container)

### ISSUE THREAD

**Issue by glenjamin** [uber/makisu#182]
I ran makisu in a container using the alpine container, as documented - which seemed to produce my image correctly.

However when I tried to `ls` it afterwards, I realised my whole filesystem had been deleted.

I realise this is probably related to my use of the `--modifyfs` feature, but I hadn't realised how intrusive the changes were going to be! Could this be noted in the documentation?

In particular, i'm experimenting with running this on CircleCI - many jobs will want to run some steps after producing the image, so it would be nice if there were a way to enable this.

Please let me know if i'm barking up the wrong tree here!

**Comment by yiranwang52** [comment]
So makisu works in 2 ways:
1. Runs outside of container, without `--modifyfs` option (default to false), in which case it doesn't support Dockerfiles with RUN.
2. Runs inside a **empty** container with only Makisu binary, with `--modifyfs=true` option. It also removes all files just in case it's not a clean environment. It supports RUN in this case.

We can make the documentation more clear.
I think your usecase can be achieved with either option.

**Comment by dnephin** [comment]
Thanks for adding to the documentation.

Is there somewhere I could read more about why it must remove all the files? I did not see that in the documentation. Are there ways to mark specific paths to prevent them from being removed?

**Comment by aweis89** [comment]
This is an issue when running makisu in Jenkins. The pipeline durability tries to execute commands in the makisu container resulting in the following:
```wrapper script does not seem to be touching the log file in /home/jenkins/workspace/g_greenhouse_new-jenkins-release@tmp/durable-d1556e1b
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found
sh: touch: not found
sh: sleep: not found```
