### ISSUE TITLE
Support for empty value for environment variable

### ISSUE THREAD

**Issue by desaintmartin** [uber/makisu#191]
In docker, it is possible to set an empty value for a variable:

`ENV MY_VARIABLE=`

Makisu does not accept this syntax. Is this a bug or a feature? This Docker "feature" is handy to unset a variable set in a previous layer (from another docker image for example).

**Comment by yiranwang52** [comment]
I guess this is a bug...

**Comment by desaintmartin** [comment]
Actually,
`ENV MY_VARIABLE=""`
Works, as expected in https://github.com/uber/makisu/blob/master/lib/parser/dockerfile/env_test.go

I suppose it is then a very low priority.

**Comment by yiranwang52** [comment]
Thanks for letting us know.

It was actually documented:
```
<value>s may contain any character, but to include whitespace it must be escaped using a backslash character or the argument must be surrounded in quotes.
```
I think current behavior is fine.
