### ISSUE TITLE
Makisu Use in K8

### ISSUE THREAD

**Issue by 2020testuser** [uber/makisu#201]
Hi,
Could someone please  help me out? This is not an issue. Need some help to use Makisu and not sure where to post.   
1. I want to use Makisu to build images and push to the docker registry from the Kubernetes cluster. So, do I need to install Makisu in my MAC or in Kubernetes? 
I have kubectl in my MAC and configured it to use my remote Kubernetes cluster.

2. Do I need any special root or elevated permissions to use Makisu or to  build and push the image using Makisu in my private registry ? 

Appreciate your help!!
If this is not the right forum, could you please let me know where to post this type of questions. Sorry again for opening this as an issue.

**Comment by yiranwang52** [comment]
1. No need to install anything, just use makisu image for you job. You can checkout our k8s setup example.
2. You don't need elevated permissions, but might need root user.

You are welcome to join our slack channel.

**Comment by 2020testuser** [comment]
Thanks Much!
I will use the slack channel. Could you please confirm whether I need to run Makes as root user. You mentioned it might need root user. I do have RUN commands and doing some installs in my Dockerfile. Appreciate your help.
Thanks in advance!

**Comment by yiranwang52** [comment]
It depends on the content of the base image and your container setup - if it's a public base image like `ubuntu:latest`, then you do need to run as root user inside the container.
