### ISSUE TITLE
Dockerhub authentication broken on master, working on 0.19?

### ISSUE THREAD

**Issue by paulcdejean** [uber/makisu#220]
I built makisu via: ` CGO_ENABLED=0 GOOS=linux go get -v github.com/uber/makisu/bin/makisu`

Then I can build an image using it, but when I try and push to dockerhub I'm getting a 401 error.

I can push to dockerhub using 0.1.9 just fine. The `--registry-config=` JSON is the same in both cases (as it's using the same .gitlab-ci.yml file).

```
      /makisu-internal/makisu build
      --modifyfs=true
      -t ${DOCKERHUB_ORG}/makisu
      --push index.docker.io
      --registry-config='
      {
        "index.docker.io": {
          ".*": {
            "security": {
              "tls": {
                "client": {
                  "disabled": false
                }
              },
              "basic": {
                "username": "${DOCKERHUB_USERNAME}",
                "password": "${DOCKERHUB_PASSWORD}"
              }
            }
          }
        }
      }'
      "${CI_PROJECT_DIR}"
```

**Comment by Rowern** [comment]
I might have introduced this regression in #208, I'm reproducing it now and I'm creating a PR to fix it.

Also for mainteners, we might want to setup a test account in docker hub with credentials in travis env to tests that we can successfully push it to the dockerhub registry.

**Comment by yiranwang52** [comment]
Agree, we do need integration test for popular registries.
