### ISSUE TITLE
Question about node_modules tweaks

### ISSUE THREAD

**Issue by Eyjafjallajokull** [uber/makisu#264]
Readme states that "Makisu has some performance tweaks for large images (especially those with node_modules)". I would like to know details about what can makisu improve when building node projects.

**Comment by yiranwang52** [comment]
The tweaks are for those builds with many text files. Specifically:
1. Faster compression and decompression library
2. More build options on compression 
3.  Doesn't require md5 hash of all files
4. Planed features like #257

**Comment by Eyjafjallajokull** [comment]
Thanks for reply.
