### ISSUE TITLE
Environment variable in ENTRYPOINT is not substituted with its value at runtime

### ISSUE THREAD

**Issue by xapon** [uber/makisu#294]
**Describe the bug**
An environment variable used in ENTRYPOINT is not substituted with its value at runtime.

**To Reproduce**
Assume a dockerfile:
```
FROM alpine:latest
ENTRYPOINT echo ${MESSAGE}
```
Build it with docker (works as expected):
```
docker build -t makisu-echo-docker .
docker run -e MESSAGE=hello makisu-echo-docker
>hello
```

Build it with makisu (unexpected output):
```
makisu_build -t makisu-echo .
docker run -e MESSAGE=hello makisu-echo
>${MESSAGE} /bin/sh
```

**Expected behavior**
I expect ENTRYPOINT to change dynamically with respect to the environment variable.
The output above should be "hello".

**Additional context**
I'm using makisu 0.1.12 and docker 19.03.3

**Comment by ericmeadows** [comment]
This is also an issue that I am having!

**Comment by Rowern** [comment]
This bug may lie inside the `lib/parser/dockerfile/replace_variables.go` file but I might be mistaken.

I will take a look at this later this week.

**Comment by Rowern** [comment]
It looks like docker create the following Entrypoint:
```json
[
  "/bin/sh",
  "-c",
  "echo ${MESSAGE}"
]
```

And makisu:
```json
[
  "echo",
  "${MESSAGE}"
]
```

**Comment by Rowern** [comment]
Anothre PR to handle the `CMD` directive that also needs this mechanism: https://github.com/uber/makisu/pull/323

**Comment by Rowern** [comment]
@yiranwang52 You can close this I think

**Comment by yiranwang52** [comment]
Yes, thanks for fixing this.
