### ISSUE TITLE
RUN directive parsing buggy

### ISSUE THREAD

**Issue by geekflyer** [uber/makisu#46]
I'm noticing a bunch of issues with makisu not being able to parse certain RUN directives that just work fine with docker build (18.06.1-ce).

If that happens I get an error message similar to this:
```
2018/11/19 00:25:14 Starting makisu (version=v0.1.0-13-gac3b5bb)
{"level":"info","ts":1542587114.7364843,"msg":"Using build context: /makisu-context"}
2018/11/19 00:25:14 Command failure: failed to get dockerfile: failed to parse dockerfile: failed to create new directive (line 16): failed to parse ECHO directive with args 'foo': Unsupported directive type
```

Here are examples which work with docker build, but not with makisu:

1. example:
```
RUN \ 
  echo foo
```
NOTICE: There is an empty space after the `\` which makes makiso choke.

2. example:
```
RUN \
  # some comment that makisu doesn't like
  echo foo
```
This example doesn't contain an empty space after `\` but it contains a `#` comment that makes makiso choke as well.

**Comment by yiranwang52** [comment]
bash doesn't allow either case, so makisu doesn't allow them either.

Docker's parser probably didn't allow these intentionally, but simply overlooked them.

**Comment by geekflyer** [comment]
After testing this myself in bash, I believe your assessment is only partially correct:
1. spaces after `\` are indeed not allowed.
2. comments in between are allowed in bash.

e.g. run the following script:
```
#!/usr/bin/env bash

echo foo && \
  # a comment
  echo bar
```

Works fine for me and prints ```
foo
bar
```

**Comment by yiranwang52** [comment]
I think it depends.
This is allowed in bash:
```
echo foo && \
  # a comment
  echo bar
```
But the following isn't:
```
echo \
  # a comment
  bar
```

I think that's because first example is equivalent of:
```
echo foo && # a comment
echo bar
```
which are 2 separate lines and is fine for bash.
However in a dockerfile, a new line needs to start with `RUN` or other keywords, so this has to be rejected.

**Comment by geekflyer** [comment]
Honestly I don't get it.
Shouldn't you thrive to make your RUN directive either docker or bash compatible instead of creating your own makisu Dockerfile flavor which is not compatible with either one?

> However in a dockerfile, a new line needs to start with RUN or other keywords...

How so? Plenty of newlines in dockerfiles in the web: https://github.com/nodejs/docker-node/blob/master/10/stretch/Dockerfile#L27 . 

Not allowing comments in multi-line RUN directives is a pretty big departure from Dockerfile syntax where having large multi-line RUN commands is common in order to reduce the layer count.

I'm aware that multi-line docker RUN directives may become somewhat obsolete when replaced with smart use of `#!COMMIT` but not allowing comments in RUN makes adoption / migration to makisu more painful than it could be.

If you are absolutely sure that you intentionally want to disallow or discourage multi-line RUN statements with comments in between I think it would be helpful to at least document this caveat / difference to regular Dockerfile's in the makisu README or throw a very explicit error message about this caveat in the parser.

**Comment by yiranwang52** [comment]
Sorry if i wasn't clear - I meant these 2 cases are equivalent in bash:
```
echo foo && \
  # a comment
  echo bar
```

```
echo foo && # a comment
echo bar
```
So the `\` essentially doesn't exist.
So it's as if you have the following dockerfile, which is certainly not allowed:
```
RUN echo foo && 
echo bar
```

We support normal usage of `\`.

**Comment by yiranwang52** [comment]
There are more users asking for better compatibility with Docker, so we decided to fix it. See #108.

**Comment by h4wkmoon** [comment]
Hi, sorry to unearth an old issue.

This directive is not parsed correctly.
`
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
`
(I know I shouldn't really not do ssh to containers. Not much choice here, and it is not the topic)

Result is :
`RUN sed -i 's/`

or did I missed something ?

**Comment by h4wkmoon** [comment]
oups.
#287
Sorry.
