### ISSUE TITLE
Support STOPSIGNAL

### ISSUE THREAD

**Issue by bjhaid** [uber/makisu#65]
While I can see that [`STOPSIGNAL` is not supported](https://github.com/uber/makisu/blob/f1dab91e97516f1a029180bf9f2362b05208b745/lib/parser/dockerfile/README.md#directives) this is somewhat relied on by most of our dockerfiles

**Comment by apourchet** [comment]
#66 was merged

**Comment by bjhaid** [comment]
@apourchet thanks that was super fast :) the doc reference has not been updated:

https://github.com/uber/makisu/blob/0189920a75a541d9d513aa5cac1fe62445772b03/lib/parser/dockerfile/README.md#directives
